config/routes.rb
Rails.application.routes.draw do
  get 'chats/index'
  get 'chats/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
   resource :favorites, only:[:create,:destroy]
   resources :book_comments, only:[:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :chats, only:[:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :book_comments, dependent: :destroy


  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comment, dependent: :destroy
  has_many :relationships, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy

  has_many :followings,through: :relationships, source: :followed
  has_many :followers,through: :reverse_of_relationships,source: :follower

  has_many :user_rooms
  has_many :chats, dependent: :destroy

  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }



  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type:'image/jpg')
    end
    profile_image.variant(resize_to_limit:[width,height]).processed

    # (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  def index
    # @book = Book.find(params[:id])
    # @ranks = Book.joins(:favorites).where(favorites: {created_at: 0.days.ago.prev_week..0.days.ago.prev_week(:sunday)}).group(:id).order("count(favorite) desc")
    # @ranks= Book.left_outer_joins(:favorites).group('favorites.id').select('favorites.*, COUNT(favorites.*) AS favorites_count').distinct.reorder(favorites_count: :desc)
    @books = Book.find(Favorite.group(:book_id).where(created_at: Time.current.all_week).order('count(book_id) desc').pluck(:book_id))
    # @books = Book.all
    @book_new = Book.new
    # @user = User.all
    @book_comment = BookComment.new
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    @books = Book.all
    if @book_new.save
      redirect_to book_path(@book_new.id), flash:{notice: "You have created book successfully."}
    else
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to "/books"
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), flash:{notice: "You have updated book successfully."}
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to "/books"
  end

  # def rank
  #   @ranks = Book.joins(:favorites).where(favorites: {created_at: 0.days.ago.prev_week..0.days.ago.prev_week(:sunday)}).group(:id.order("count(*) desc"))
  # end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_room = UserRoom.find_by(user_id: @user.id, room_id: rooms)
    if user_room.nil?
      @room = Room.create()
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    else
      @room = user_room.room
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
      if @range == "User"
        @users = User.looks(params[:search],params[:word])
      else
        @books = Book.looks(params[:search],params[:word])
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
  end

  def index
    @users = User.all
    @book_new = Book.new
    # @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render:edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), flash:{notice: "You have updated user successfully."}
    else
      render:edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<% if @book_new.errors.any? %>
   <ul class="alert alert-light text-danger" role="alert">
    <h6 class="alert-heading">
      <%= pluralize(@book_new.errors.count,"error") %> prohibited this obj from being saved:
    </h6>
  <% @book_new.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
   </ul>
 <% end %>

<%= form_with model:@book_new,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(40,40) %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td id="favorite-btn-<%= book.id %>">
            <%= render "favorites/favorite-btn", book: book %>
        </td>
        <td>
            コメント数: <%= book.book_comments.count %>
            <!--#{book.book_comments.count} コメント-->
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_rank.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book, i| %>
      <tr>
        <td><%= link_to (book.user) do %>
          <%= image_tag book.user.get_profile_image(40,40) %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td id="favorite-btn-<%= book.id %>">
            <%= render "favorites/favorite-btn", book: book %>
        </td>
        <td>
            コメント数: <%= book.book_comments.count %>
            <!--#{book.book_comments.count} コメント-->
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<% if @book.errors.any? %>
     <ul class="alert alert-light text-danger" role="alert">
      <h6 class="alert-heading">
        <%= pluralize(@book.errors.count,"error") %> prohibited this obj from being saved:
      </h6>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
     </ul>
    <% end %>
  		<!--<= render 'form', book: @book %>-->
  	<%= form_with model:@book,local:true do |f| %>
      <div class="form-group">
        <h4>Title</h4>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <h4>Opinioon</h4>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="form-group">
      <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>


  		<%= link_to 'Show', book_path(@book.id) %> |
  		<%= link_to 'Back', "/books" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'rank', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <!--<= render 'users/info' %>-->
      <table class='table'>
      <tr><%= image_tag @user.get_profile_image(100,100) %></tr>
      <tr>
    	  <th>name</th>
	      <th><%= @user.name %></th>
      </tr>
      <tr>
	      <th>introduction</th>
	      <th><%= @user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= link_to @user.followings.count,user_followings_path(@user.id) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to @user.followers.count,user_followers_path(@user.id) %></th>
      </tr>
    </table>
      <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>




      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr id="book_<%= @book.id %>">
          <td><%= link_to(@user) do %>
            <%= image_tag @user.get_profile_image(100,100) %><br>
            <%= @user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
            <!--< if @book.user_id == current_user.id %>-->
            <!--  <td><= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>-->
            <!--  <td><= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>-->
            <!--< else %>-->
            <!--  <td colspan="2"></td>-->
            <!--< end %>-->
          <td class="favorite-btn"><% if @book.favorited_by?(current_user) %>
              <p class="text-danger">
                <%= link_to book_favorites_path(@book),method: :delete,remote: true, class:"text-danger" do %>
                ♥︎<%= @book.favorites.count %>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(@book),method: :post,remote: true do %>
                ♡<%= @book.favorites.count %>
                <% end %>
              </p>
                <% end %>
          </td>
          <td>
            <p>コメント数:<%= @book.book_comments.count %></p>
          </td>
        </tr>
      </table>

      <table class="table table-borderless">
        <% @book.book_comments.each do |book_comment| %>
        <tr>
          <td>
              <p><%= image_tag book_comment.user.get_profile_image(50,50) %></p>
              <%= book_comment.user.name %>
          </td>
          <td>
            <%= book_comment.comment %>
          </td>
          <td><% if book_comment.user == current_user %>
          <%= link_to 'Destroy', book_book_comment_path(book_comment.book,book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
              <% end %>
          </td>
            <% end %>
        </tr>
      </table>



      <%= form_with model:[@book,@book_comment] do |f| %>
          <%= f.text_area :comment, size:'90x5' %>
          <%= f.submit "送信" %>
      <% end %>

      </div>
    </div>
  </div>
</div>

app/views/chats/_message.html.erb
<div class="message">
  <p>
    <%# 部分テンプレートで渡ってくるcurrent_user内に、ユーザー情報がなければActionCable経由として判断 %>
    <% if current_user.nil? %>
      <%# DBから受け取る場合の表示 %>
      <small><%= message.user.email %></small><br>
      <%= message.message %>
    <% else %>
      <%# ActionCableから受け取る場合の表示 %>
      <small><%= current_user.email %></small><br>
      <%= message['message'] %>
    <% end %>
  </p>
</div>

app/views/chats/index.html.erb
<h1>Chats#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<ul>
  <% @users.each do |user| %>
    <% if current_user != user %>
      <li>
        <%= link_to"#{user.email}とチャットする", chat_path(user.id) %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/chats/show.html.erb
<h1>Chats#show</h1>
<p>Find me in app/views/chats/show.html.erb</p>

<div id="chats" data-room_id="<%= @room.id %>">
  <label for="message">Chat Text</label><br>
  <textarea name="message" id="message" cols="30" rows="10"></textarea><br>
  <small>Shift + Enterで送信</small>
  <h2>Chats --></h2>
  <% @room.chats.each do |message| %>
    <%= render partial: 'message', locals: { message: message, current_user: nil } %>
  <% end %>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>フォロー:<%= user.followings.count %></td>
        <td>フォロワー:<%= user.followers.count %></td>
        <td><% unless user.id == current_user.id %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>
            <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag current_user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= current_user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= current_user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count,user_followings_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count,user_followers_path(user.id) %></th>
  </tr>
</table>

<div class='row'>

  <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= render 'layouts/errors', obj: @user %>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>


  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <!--<= render 'info', user: @user %>-->
      <table class='table'>
      <tr><%= image_tag @user.get_profile_image(100,100) %></tr>
      <tr>
    	  <th>name</th>
	      <th><%= @user.name %></th>
      </tr>
      <tr>
	      <th>introduction</th>
	      <th><%= @user.introduction %></th>
      </tr>
       <tr>
        <th>follows</th>
        <th><%= link_to @user.followings.count,user_followings_path(@user.id) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to @user.followers.count,user_followers_path(@user.id) %></th>
      </tr>
    </table>
      <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>


    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>